Repository ufv-crp/Music, pull requests merged in 2020-02, with the labels that each got.

#42 Optional token on create authenticated client
  src/authentication/client.js
  src/pages/login/login.js
Labels: enhancement

#45 Account Page
  package.json
  src/components/account/details/details.js
  src/components/account/profile/profile.js
  src/components/header/header.js
  src/components/index.js
  src/components/sidebar/profile/profile.js
  src/components/sidebar/sidebar.js
  src/components/user/address/address.js
  src/components/user/contact/contact.js
  src/components/user/index.js
  src/index.js
  src/layouts/general/general.js
  src/pages/account/account.js
  src/pages/account/api.js
  src/pages/login/login.js
Labels: enhancement

#60 Breadcrumbs
  src/components/breadcrumbs/breadcrumbs.js
  src/components/index.js
  src/layouts/general/general.js
Labels: enhancement, template

#59 Course page
  package.json
  src/components/header/header.js
  src/pages/courses/api.js
  src/pages/courses/courses.js
  src/pages/courses/styles.js
  src/pages/login/login.js
  src/states/utils.js
Labels: enhancement

#64 Class page CRUD
  package.json
  public/index.html
  src/components/materialTable/icons.js
  src/layouts/general/styles.js
  src/pages/classes/api.js
  src/pages/classes/classes.js
Labels: enhancement

#65 Center login page and show success and error message on login / forgot password
  .github/workflows/nodejs.yml
  .gitignore
  package.json
  public/favicon.ico
  public/images/icons/icon-128x128.png
  public/images/icons/icon-144x144.png
  public/images/icons/icon-152x152.png
  public/images/icons/icon-192x192.png
  public/images/icons/icon-384x384.png
  public/images/icons/icon-512x512.png
  public/images/icons/icon-72x72.png
  public/images/icons/icon-96x96.png
  public/images/logos/logo.black.png
  public/images/logos/logo.colorful.png
  public/images/logos/logo.header.png
  public/images/logos/logo.note.white.png
  public/images/logos/logo.white.png
  public/index.html
  public/manifest.json
  public/robots.txt
  src/application.js
  src/authentication/authenticate.js
  src/index.js
  src/pages/login/login.js
  src/pages/login/styles.js
Labels: bug, enhancement

#71 Style nestedted table
  src/components/account/details/details.js
  src/components/header/header.js
  src/layouts/general/general.js
  src/pages/classes/classes.js
  src/pages/courses/courses.js
  src/pages/login/login.js
Labels: bug, enhancement
